# Generated by Django 4.1.7 on 2023-02-27 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=512)),
                ('img_url', models.URLField(max_length=256)),
                ('create_date', models.DateField()),
                ('start_bid', models.FloatField()),
                ('best_bid', models.FloatField()),
                ('best_bidder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='current_winner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
