# Generated by Django 4.1.7 on 2023-02-27 17:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='best_bid',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='best_bidder',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_winner', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='listing',
            name='img_url',
            field=models.URLField(blank=True, max_length=256),
        ),
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.FloatField(blank=True),
        ),
    ]
