# Generated by Django 4.1.7 on 2023-02-27 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_alter_listing_best_bid_alter_listing_best_bidder_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='start_bid',
            field=models.FloatField(),
        ),
    ]
