# Generated by Django 4.1.7 on 2023-02-27 17:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_listing_start_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='best_bid',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='listing',
            name='best_bidder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_winner', to=settings.AUTH_USER_MODEL),
        ),
    ]
