# Generated by Django 4.1.7 on 2023-03-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('1', 'FASHION'), ('2', 'TOYS'), ('3', 'ELECTRONICS'), ('4', 'HOME'), ('5', 'OTHERS')], default='5', max_length=2),
        ),
    ]
