# Generated by Django 4.1.7 on 2023-03-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0019_listing_is_active_alter_listing_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
