# Generated by Django 4.1.7 on 2023-03-10 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_alter_listing_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='category',
        ),
    ]
