# Generated by Django 4.1.7 on 2023-03-10 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0024_remove_listing_is_active_listing_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
